name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        rid: [win-x64, win-x86, linux-x64, osx-x64, osx-arm64]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: |
        for proj in $(ls *.csproj); do
          dotnet publish $proj -c Release -r ${{ matrix.rid }} -p:PublishSingleFile=true --self-contained -p:DebugSymbols=false -o ./publish/${{ matrix.rid }}
        done
    - name: Tree
      run: |
        sudo apt -y install tree
        tree
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: myapp-${{ matrix.rid }}
    #     path: ./publish/${{ matrix.rid }}
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
